const languages = [
   'Português (Brasil)',
   'English (US)',
   'Español',
   'Français (France)',
   'Italiano',
   'العربية',
   'Deutsch',
   'हिन्दी',
   '中文(简体)',
   '日本語',
];

const actions = [
   'Cadastre-se',
   'Entrar',
   'Messenger',
   'Facebook Lite',
   'Watch',
   'Pessoas',
   'Páginas',
   'Categorias de Página',
   'Locais',
   'Jogos',
   'Locais',
   'Marketplace',
   'Facebook Pay',
   'Grupos',
   'Vagas de emprego',
   'Oculus',
   'Portal',
   'Instagram',
   'Local',
   'Campanhas de arrecadação de fundos',
   'Serviços',
   'Central de Informações de Votação',
   'Sobre',
   'Criar anúncio',
   'Criar Página',
   'Desenvolvedores',
   'Carreiras',
   'Privacidade',
   'Cookies',
   'Escolhas para anúncios',
   'Termos',
   'Ajuda',
];

export { languages, actions };
